name: Deploy 

on: 
  push:
     branches: 
     - main
jobs:
  deploy_lambda:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '18.x'
      - name: npm install
        env: 
          CI: true
        run: |
          npm ci: 
          
